# KPort hardware compatibility configuration
# Generated by: kport detect
# Generated on: {{GENERATED_DATE}}
#
# This file is read by KPort at install/build time to automatically set
# hardware-appropriate USE flags. Edit manually to override detection.
#
# Re-run detection: kport detect --update
# Show what flags this enables: kport detect --show-flags

# ── CPU ───────────────────────────────────────────────────────────────────────
# x86-64-v1: baseline (SSE, SSE2)
# x86-64-v2: SSE3, SSSE3, SSE4.1, SSE4.2, POPCNT
# x86-64-v3: AVX, AVX2, BMI1, BMI2, FMA, MOVBE, XSAVE
# x86-64-v4: AVX-512 (F, BW, CD, DQ, VL)
# aarch64:   64-bit ARM baseline
# aarch64-v8.2: ARMv8.2 (SVE, dotprod, fp16)
CPU_TIER="{{CPU_TIER}}"
CPU_FLAGS="{{CPU_FLAGS}}"
CPU_CORES="{{CPU_CORES}}"
CPU_MODEL="{{CPU_MODEL}}"

# ── GPU ───────────────────────────────────────────────────────────────────────
# gpu-sw:    software rendering only
# gpu-gl2:   OpenGL 2.x
# gpu-gl4:   OpenGL 4.x + Vulkan 1.0
# gpu-vk12:  Vulkan 1.2 + compute shaders
# gpu-vk13:  Vulkan 1.3 + mesh shaders
GPU_TIER="{{GPU_TIER}}"
GPU_VENDOR="{{GPU_VENDOR}}"
GPU_FLAGS="{{GPU_FLAGS}}"
GPU_MODEL="{{GPU_MODEL}}"
GPU_VRAM_MB="{{GPU_VRAM_MB}}"

# ── NPU ───────────────────────────────────────────────────────────────────────
# npu-none:        no NPU, CPU inference only
# npu-igpu:        iGPU compute via OpenCL
# npu-dedicated:   dedicated NPU, limited TOPS (<10)
# npu-ai:          full AI accelerator (>=10 TOPS)
# npu-datacenter:  datacenter-class accelerator
NPU_TIER="{{NPU_TIER}}"
NPU_FLAGS="{{NPU_FLAGS}}"
NPU_MODEL="{{NPU_MODEL}}"
NPU_TOPS="{{NPU_TOPS}}"

# ── Derived USE flags ─────────────────────────────────────────────────────────
# These are computed from the tiers above and applied automatically.
# Set to "manual" to disable auto-derivation for a specific flag.
USE_VULKAN="{{USE_VULKAN}}"
USE_VAAPI="{{USE_VAAPI}}"
USE_VDPAU="{{USE_VDPAU}}"
USE_CUDA="{{USE_CUDA}}"
USE_ROCM="{{USE_ROCM}}"
USE_OPENCL="{{USE_OPENCL}}"
USE_NPU="{{USE_NPU}}"
USE_LLM_LOCAL="{{USE_LLM_LOCAL}}"
